[build]
  # The command to build your project
  command = "npm run build"
  
  # The directory that contains the deploy-ready HTML/assets
  publish = "dist"

  # (Optional) Directory for serverless functions
  functions = "netlify/functions"

[[redirects]]
  # This rule is often needed for Single Page Applications (SPAs)
  from = "/*"
  to = "/index.html"
  status = 200
